name: CI

on:
    push: ~
    pull_request: ~

permissions: read-all

jobs:
    ci:
        uses: 'terminal42/contao-build-tools/.github/workflows/build-tools.yml@main'

    tests:
        name: 'Unit tests (PHP ${{ matrix.php }}, Composer Flags: ${{ matrix.composer }})'
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.3', '8.4', '8.5' ]
                composer: [ '--prefer-stable', '--prefer-lowest' ]
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  show-progress: false
                  persist-credentials: false

            - name: Install the dependencies
              run: composer update --no-interaction ${{ matrix.composer }}

            - name: Run phpunit
              run: composer unit
